class Patterns:
    help_pattern = r'\A<[^>]*> help\Z'
    delete_template_pattern = r'\A<[^>]*> delete template (\S+)'
    delete_bot_pattern = r'\A<[^>]*> delete bot (\S+)'
    show_templates_pattern = r'\A<[^>]*> show templates'
    show_bots_pattern = r'\A<[^>]*> show bots'
    show_bot_pattern = r'\A<[^>]*> show bot (\S+)'
    create_bot_pattern = r'\A<[^>]*> create bot (\S+)'
    set_template_to_bot_pattern = r'\A<[^>]*> set (\S+) template (\S+)\Z'
    set_frequency_to_bot_pattern = r'\A<[^>]*> set (\S+) frequency (\S+)\Z'
    set_keywords_to_bot_pattern = r'\A<[^>]*> set (\S+) keywords (\S+)\Z'
    set_tones_to_bot_pattern = r'\A<[^>]*> set (\S+) tones (\S+)\Z'
    create_template_pattern = r'\A<[^>]*> create template (\S+) ?(\S[\s\S]*)?\Z'
    run_bot_pattern = r'\A<[^>]*> run (\S+)'
    set_template_pattern = r'\A<[^>]*> set template (\S+) ?(\S[\s\S]*)?\Z'